### 1. Alle GeoTags abrufen

GET http://localhost:3000/api/geotags


### 2. Ein neues GeoTag erstellen (POST)

POST http://localhost:3000/api/geotags
Content-Type: application/json

{
    "name": "HKA Bib",
    "latitude": "49.0152",
    "longitude": "8.3905",
    "hashtag": "#lernen"
}


### 3. Ein bestimmtes GeoTag abrufen (GET mit ID)

GET http://localhost:3000/api/geotags/12


### 4. Ein GeoTag ändern (PUT)

PUT http://localhost:3000/api/geotags/12
Content-Type: application/json

{
    "name": "HKA Bibliothek",
    "latitude": "49.0152",
    "longitude": "8.3905",
    "hashtag": "#klausurenphase"
}


### 5. Ein GeoTag löschen (DELETE)

DELETE http://localhost:3000/api/geotags/12


### 6. Umkreissuche testen (GET mit Query-Parametern)
GET http://localhost:3000/api/geotags?latitude=49.013790&longitude=8.404435&searchterm=castle

### 7. Pagination testen - Seite 1
GET http://localhost:3000/api/geotags?latitude=49.013790&longitude=8.390071&page=1&limit=5


### 8. Pagination testen - Seite 2
GET http://localhost:3000/api/geotags?latitude=49.013790&longitude=8.390071&page=2&limit=5


### 9. Pagination mit Suchbegriff
GET http://localhost:3000/api/geotags?latitude=49.013790&longitude=8.390071&searchterm=campus&page=1&limit=3